package router

import (
	"bufio"
	"fmt"
	"io"
	"strings"
)

// LoadRoutes reads a route manifest from r and registers each entry into t.
// It is meant for route tables generated by another system (a build step,
// a service registry dump, a config sync) that can grow to millions of
// lines. r is read with a bufio.Scanner one line at a time, so LoadRoutes
// never holds more than a single line in memory regardless of the total
// input size, unlike reading the whole source with io.ReadAll first.
//
// Each non-blank, non-comment line has the form:
//
//	METHOD PATTERN TAG
//
// Fields are separated by single spaces or tabs; extra whitespace is
// ignored. Lines starting with '#' (after trimming leading whitespace) are
// comments and skipped, as are blank lines.
//
// LoadRoutes stops at the first malformed line or registration conflict and
// returns an error naming the line number. It returns the number of routes
// successfully loaded before the error, if any.
func LoadRoutes(t *Table, r io.Reader) (int, error) {
	scanner := bufio.NewScanner(r)
	loaded := 0
	lineNo := 0

	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) != 3 {
			return loaded, fmt.Errorf("router: line %d: want 3 fields (method pattern tag), got %d", lineNo, len(fields))
		}

		method, pattern, tag := fields[0], fields[1], fields[2]
		if err := t.Handle(method, pattern, tag); err != nil {
			return loaded, fmt.Errorf("router: line %d: %w", lineNo, err)
		}
		loaded++
	}
	if err := scanner.Err(); err != nil {
		return loaded, fmt.Errorf("router: reading manifest: %w", err)
	}
	return loaded, nil
}
